#!/bin/bash

if [ ! -d "build/.git" ]; then
  echo "Please run the setup script before first deployment."
  exit
fi

git add . --all
git commit -m "$1" --allow-empty
git push origin +develop

middleman build

cd build

git add . --all
git commit -m "$1" --allow-empty
git push origin +master