#!/bin/bash

if [ ! -d "build/.git" ]; then
  echo "Please run the setup script before first deployment."
  exit
fi

if [ -z "$1" ]; then
    echo "Usage: script/deploy 'Commit message'"
    exit
fi

git add . --all
git commit -m "$1" --allow-empty
git push origin +develop

middleman build

cd build

git add . --all
git commit -m "$1" --allow-empty
git push origin +master